spring:
  application:
    name: service-enterprise
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/daijia?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.atguigu.daijia.model.entity

server:
  port: 8003
  servlet:
    context-path: /

logging:
  level:
    com.atguigu.daijia: debug
    org.springframework: info
